### ISSUE TITLE
Game still never ends when someone left it.

### ISSUE THREAD

**Issue by Kant8** [arcadia-redux/overthrow2#110]
As title says, whenever there are a leaver in game, neither score nor timer cannot end game.

**Comment by darklordabc** [comment]
Thanks for reporting this. We are aware of this problem and we are trying to fix it now.

**Comment by Kant8** [comment]
On last version game ended ok. Our first time since bug when there were leavers.

**Comment by darklordabc** [comment]
So its ending well?

**Comment by Kant8** [comment]
Unfortunately we had only 1 game with leaves, but yes, it's ended well.
