### ISSUE TITLE
July Overthrow 2.0 Update

### ISSUE THREAD

**Issue by darklordabc** [arcadia-redux/overthrow2#119]
- [ ] Add 24 Player FFA Map
- [x] Add all extra perks from 12v12
- [x] Add Viewable Leaderboards like in 12v12
- [x] Add new items to shop menu if not added already (do same for 12v12)
- [x] Add MMR Ranking per map
- [x] Ensure Item Transfer Perk is working as intended #118 
- [x] Import all scoreboard improvements from 12v12
- [x] Make sure cosmetic settings and voice line favorites are saving properly
- [ ] Import Voting Options from 12v12. Increase Time and Score Limit. 
- [x] Remove slow motion at the start of game from all other maps, except octet
- [x] Remove mango of appreciation (from 12v12 too)
- [x] Make it so the overboss throws out neutral items again. Players need to stand in the area to "capture" the neutral item, cannot have other enemies in the capture area. Remove neutral items from normal delivery chests. 
- [x] Dramatically Reduce Lone Druid summon bear ability cooldown.
- [x] Reduce cooldown (or make it charge base) of doom drastically, and maybe reduce its duration by half. 
- [x] Make Shadow Demon Get Souls Passively

**Comment by Sheodar** [comment]
- Add Viewable Leaderboards like in 12v12
Added, but need update webapi/server side
