### ISSUE TITLE
Potential Items to Add to Overthrow

### ISSUE THREAD

**Issue by darklordabc** [arcadia-redux/overthrow2#123]
Current Items
NEUTRAL_ITEMS = {
	[1] = {
		"item_health_potion",
		"item_keen_optic",
		"item_poor_mans_shield",
		"item_iron_talon",
		"item_ironwood_tree",
		"item_royal_jelly",
		"item_mango_tree",
		"item_ocean_heart",
		"item_broom_handle",
		"item_trusty_shovel",
		"item_faded_broach",
		"item_arcane_ring",
	},
	[2] = {
		"item_grove_bow",
		"item_vampire_fangs",
		"item_ring_of_aquila",
		"item_pupils_gift",
		"item_imp_claw",
		"item_philosophers_stone",
		"item_nether_shawl",
		"item_dragon_scale",
		"item_essence_ring",
		"item_clumsy_net",
		"item_vambrace",
	},
	[3] = {
		"item_helm_of_the_undying",
		"item_craggy_coat",
		"item_greater_faerie_fire",
		"item_quickening_charm",
		"item_mind_breaker",
		"item_spider_legs",
		"item_enchanted_quiver",
		"item_paladin_sword",
		"item_orb_of_destruction",
		"item_third_eye",
		"item_titan_sliver",
	},
	[4] = {
		"item_witless_shako",
		"item_timeless_relic",
		"item_spell_prism",
		"item_princes_knife",
		"item_flicker",
		"item_ninja_gear",
		"item_illusionsts_cape",
		"item_havoc_hammer",
		"item_panic_button",
	},
	[5] = {
		"item_force_boots",
		"item_desolator_2",
		"item_phoenix_ash",
		"item_seer_stone",
		"item_mirror_shield",
		"item_fusion_rune",
		"item_ballista",
		"item_woodland_striders",
		"item_demonicon",
		"item_fallen_sky",
		"item_pirate_hat",
		"item_ex_machina",
		"item_apex",
	}

**Comment by darklordabc** [comment]
Add this item as tier 2, but lower cooldown to 20 seconds. 
![image](https://user-images.githubusercontent.com/16277198/90145587-6caf2400-ddc3-11ea-9c50-a64163825a47.png)

**Comment by darklordabc** [comment]
Add this item as a tier 5 item
![Uploading image.png…]()

**Comment by darklordabc** [comment]
Tier 3 item
![image](https://user-images.githubusercontent.com/16277198/90146274-31f9bb80-ddc4-11ea-9f4e-8bf194704f33.png)

**Comment by darklordabc** [comment]
Tier 2 item
![image](https://user-images.githubusercontent.com/16277198/90146542-813fec00-ddc4-11ea-809a-e17e75f445f1.png)

**Comment by darklordabc** [comment]
Tier 1 item
![image](https://user-images.githubusercontent.com/16277198/90146644-a2084180-ddc4-11ea-834c-2bc31b967f79.png)

**Comment by darklordabc** [comment]
Tier 5 
![image](https://user-images.githubusercontent.com/16277198/90146748-c401c400-ddc4-11ea-81dc-cdcc7363752c.png)

**Comment by darklordabc** [comment]
Tier 3
![image](https://user-images.githubusercontent.com/16277198/90146888-f3183580-ddc4-11ea-8566-f3ef810da140.png)

**Comment by darklordabc** [comment]
Tier 1 
![image](https://user-images.githubusercontent.com/16277198/90147039-19d66c00-ddc5-11ea-9312-7d28d3157927.png)

**Comment by Sheodar** [comment]
Added all from this list + more items from aghs labh
