### ISSUE TITLE
Chen can cause massive framerate drops by making infinite ancient creeps and then spamming move commands.

### ISSUE THREAD

**Issue by Antelope13** [arcadia-redux/overthrow2#138]
This Chen sat in base and made lots of ancient creeps. When he would give them move commands, my framerate would drop from ~120ish to ~1ish for a couple seconds.

![570_20210331170716_1](https://user-images.githubusercontent.com/1731494/113215475-e4de3300-9248-11eb-9deb-7b303a11d9a3.png)

**Comment by iprobie** [comment]
can confirm, there's no limit to creeps spawned by Soul Persuasion skill
