### ISSUE TITLE
Better Anti Feeding System

### ISSUE THREAD

**Issue by iprobie** [arcadia-redux/overthrow2#140]
At the moment, the anti feeding system only works when the fountain kills the feeder.
This is a very poor anti-feeding safeguard and needs to be massively improved.

Couple of suggestions:
-Use statistics and rules. if a player dies more than 2 times in the last 60 seconds and have more than an average of 2 deaths per minute, the system kicks in.
The player would then have its next death have 20 sec extra respawn timer, have their respawn/fountain movement speed boost disabled (for desert_octet), and have their buyback disabled for 60 seconds. 

-If a player has abandoned, disable its movement and do not allow it to be moved/controlled around by allies. Abandoning players rarely ever make a difference because they cant buy items and any gold they make is given to the rest of the team instead.

**Comment by darklordabc** [comment]
Some good suggestions here

**Comment by giganticcrater** [comment]
some time  I have to feed to win ，die more  to fully use COMBAT READINESS ，so my fv can cast more ult to kill clinkz ，or pom‘s team 
sad
