### ISSUE TITLE
"Disable Help" ignores item abuse

### ISSUE THREAD

**Issue by Antelope13** [arcadia-redux/overthrow2#146]
In my last game, Tiny kept tossing my teammates into the yellow team I told my team how to disable help and they did. Tiny could no longer toss us into the yellow team.

Tiny bought Ethereal Blade and Wind Waker to prevent me from doing damage. He bought Octarine Core, Refresher Orb, and Arcane Blink so he could use Ethereal Blade and Wind Waker almost constantly. I was almost completely disabled for the entire second half of the game. Yellow team barely won, and would have lost if Tiny wasn't helping them.

I know you are petitioning Valve to improve matchmaking rules for custom games, to prevent trolls. I hope that Valve makes these improvements, but it is possible that they do not. Two that could fix the problem:
1. "Disable Help" also disables items. This helps everyone.
2. I receive the ability to kick trolls without financial support. I was a financial supporter for a long time. I've submitted multiple high-quality issue reports, and will continue to do so because I like this game and want it to improve. This helps whatever team I am playing on, but is not as fair.

**Comment by Antelope13** [comment]
![570_20210514202553_1](https://user-images.githubusercontent.com/1731494/118343696-5b34ad00-b4f8-11eb-9e4e-3a23b809718a.png)

**Comment by Sheodar** [comment]
Updated list for disabled help (abilities/items/neutral items)
