### ISSUE TITLE
Perks values and tooltips don't match up from last udpate

### ISSUE THREAD

**Issue by AustraliaIsMyCity** [arcadia-redux/overthrow2#148]

**Comment by Sheodar** [comment]
@Draze22 close this, u fixed this already.

**Comment by Draze22** [comment]
Fixed:
English: https://github.com/arcadia-redux/overthrow2/commit/9929cb22f13e95a96f93e2fbfc20374510d4188e.
Russian: https://github.com/arcadia-redux/overthrow2/commit/6a2fc218d1b3d067087ec1fd4a88998a82e568c2.
Chinese: https://github.com/arcadia-redux/overthrow2/commit/3128902b998a133d6a0a28ec7e4ea43c7833eefe.
