### ISSUE TITLE
Major gamebreaking bug. Delayed Damage perk provides immortality. Needs to be disabled or fixed immediately.

### ISSUE THREAD

**Issue by Antelope13** [arcadia-redux/overthrow2#149]
Wraith King's Aghanim's Scepter upgrade adds the "Wraith Delay" aura to his teammates. Whenever Wraith King, or one of his allies, die they are transformed into a wraith for 7 seconds. After the 7 second duration, they die. However, any heroes that have the Delayed Damage perk return to life with 1 HP. If they die a second time, the same thing happens and they will continue to cycle between living -> wraith forever.

From what I can tell, Wraith Delay drops the hero to 1 HP, and at the end of its duration it deals enough damage to kill the hero. Since the damage it delayed, it doesn't kill the hero. 

I just faced a terrible team that abused this bug. Two players, Huskar and Wraith King both, both picked Delayed Damage and we could not kill them. They died over and over but kept coming back to life.

Their steam profiles: 
- Huskar (SAKI, Friend ID 204855175): https://steamcommunity.com/profiles/76561198165120903/
- Wraith King (Untiltable Mountain, Friend ID 157297935):  https://steamcommunity.com/profiles/76561198117563663/

![570_20210524202837_1](https://user-images.githubusercontent.com/1731494/119423570-917ce400-bcd1-11eb-8672-7979957ddd04.png)

**Comment by Sheodar** [comment]
Imported fix from 12v12
