### ISSUE TITLE
Reconnecting to a game crashes the server

### ISSUE THREAD

**Issue by Draze22** [arcadia-redux/overthrow2#152]
![image](https://user-images.githubusercontent.com/63279022/125911123-cb91a1d5-333e-4d1f-86b0-2d7f1f3ea500.png)
![image](https://user-images.githubusercontent.com/63279022/125911194-ce07cb67-13b3-4cc8-84db-bd7d02895488.png)

**Comment by Draze22** [comment]
Confirmed, if a player reconnects to the game it crashes the server.

![image](https://user-images.githubusercontent.com/63279022/125938067-b2eb7834-91d1-4b8c-9e2d-d1b563cb8ccd.png)

**Comment by Sheodar** [comment]
Fixed. Need little time for upload this in live game version.
