### ISSUE TITLE
Check if there is a problem with being able to press extend score/kill limit many times

### ISSUE THREAD

**Issue by ArcadiaReduxAutomation** [arcadia-redux/overthrow2#155]
When tested solo I could do it over and over again

Opened from Discord by **darklord#6168**
Follow the conversation [here](https://discord.com/channels/501306949434867713/828460929427046430/867117843438370826)

**Comment by Draze22** [comment]
![image](https://user-images.githubusercontent.com/63279022/126380871-309b8a04-6d72-4639-b28a-97d4e2184e92.png)
