### ISSUE TITLE
Picking Sniper crashes the game

### ISSUE THREAD

**Issue by Draze22** [arcadia-redux/overthrow2#160]
Isn't consistent.

**Comment by Draze22** [comment]
![image](https://user-images.githubusercontent.com/63279022/132283874-4fb57386-4205-4172-90ff-34e0ca1d5223.png)

**Comment by Draze22** [comment]
Can confirm that picking Sniper crashes Dota.

**Comment by Draze22** [comment]
The same thing does not happen with Alchemist.

**Comment by Draze22** [comment]
> Can confirm that picking Sniper crashes Dota.

Picked Sniper a second time and the game didn't crash.

**Comment by ArcadiaReduxAutomation** [comment]
## Warning  
This issue was inactive for **7** days with label "needs confirmation".  
It will be **closed** automatically after **7** days if this issue stays inactive.
