### ISSUE TITLE
When a player leaves, decrease the kill goal by 5

### ISSUE THREAD

**Issue by ArcadiaReduxAutomation** [arcadia-redux/overthrow2#166]
may revisit value later if its not effective, may also need to modify fountain invulnerability to prevent games stalling forever

Opened from Discord by **non toxic egirl#1202**
Follow the conversation [here](https://discord.com/channels/501306949434867713/501306949434867715/889327650995339294)

**Comment by Sheodar** [comment]
Added with value 5
