### ISSUE TITLE
Recent Dota update broke sounds in Overthrow

### ISSUE THREAD

**Issue by Antelope13** [arcadia-redux/overthrow2#184]
Today I joined a game of Overthrow Octet. From the beginning of the game, a loud "portal" sound effect started playing. Throughout the game, it got louder and louder until I couldn't hear game sounds. It is played on the audio channel "Game Sounds", so muting it means that you can't hear any of the game's sound effects.

I started an Octet lobby with no other players and there were no sound issues.

Then I joined second game of Octect, and the issue returned. This time, instead of "portal" sounds, I heard metal music being played. Once again, it was so loud that I couldn't hear game sounds.

Multiple players from all teams confirmed that it was a problem for them as well.

**Comment by Antelope13** [comment]
Just played a third game. Same issue. The sounds are tied to the exact center of the map. If you scroll to the edges, you can barely hear them. But in the center of the map the sounds are unbearable.

**Comment by Draze22** [comment]
These sounds happen in Aghs Lab 2 aswell, pretty sure only Valve can fix them.
