### ISSUE TITLE
2 bugs

### ISSUE THREAD

**Issue by GizmoFestus** [arcadia-redux/overthrow2#189]
1) Most of voice lines are inhearable. The text appears in chat, but but with no voice. Example: some voices from -ch 300 to -ch 989
2) Desert octet minimup is glitched
![изображение](https://user-images.githubusercontent.com/96342745/149627417-8f7c419a-e027-4c4d-a0c3-286d09110505.png)
good minimap view:
![изображение](https://user-images.githubusercontent.com/96342745/149627458-bfe174ea-01ee-4d7d-ac16-506762530ed8.png)

**Comment by Draze22** [comment]
The voicelines is due to our work around to the audio bug.
