### ISSUE TITLE
Players can possibly share items

### ISSUE THREAD

**Issue by Draze22** [arcadia-redux/overthrow2#194]
![image](https://user-images.githubusercontent.com/63279022/152628555-13a8c61d-f6b2-4b07-8211-dacbb0400253.png)

**Comment by ZLOY5** [comment]
This is clearly done on purpose, but not sure why.
https://github.com/arcadia-redux/overthrow2/blob/master/game/scripts/npc/npc_abilities_override.txt#L17-L223

**Comment by ZLOY5** [comment]
Seems that leftovers of old overthrow item drop system, that waas changed to perks drop

**Comment by ZLOY5** [comment]
This bug was so long in game, more than year.
