### ISSUE TITLE
Potential Gamebreaking Combination

### ISSUE THREAD

**Issue by iprobie** [arcadia-redux/overthrow2#195]
In Overthrow, since the map is small and fountain gives a lot of regen, this combo has the potential to be broken.

The combo requires you to play Rubick with Aghanim Scepter (which steals 2 spells) and then steal Earthshaker's Fissure with Aghanim Shard equipped. Then you combine this with a 0 cd ability spell such as Ball Lightning.

You will then be able to proc infinite Aftershock in a short amount of time around your Fissure, pretty much permastunning and gibbing non-tanky targets. Problem is made worse for desert_octet map where Storm Spirit and Earthshaker are common picks, while also having instant full regen in fountain for Rubick.

**Comment by iprobie** [comment]
I really don't know what to do about this other than maybe giving Rubick Fissure steal no Aftershock but that'd make regular Rubick games a bit worse

**Comment by Draze22** [comment]
We'll probably let Valve fix this combo first since it exists in vanilla Dota too.
