### ISSUE TITLE
Meepo does not fully benefit from "+Agi/Str/Int per Kill" perks

### ISSUE THREAD

**Issue by 54ki** [arcadia-redux/overthrow2#196]
Main Meepo does not benefit from perks such as Little Ranger, Little Butcher, etc. It seems each clone has its own seperate perk and whichever clone gets the kill will get the attribute bonus. This is very wasteful. The bonus per kill should be rewarded to the Main Meepo instead, so that every clone gets the bonuses equally.

**Comment by Sheodar** [comment]
Fixed for OT2 and 12v12
