### ISSUE TITLE
Gamebreaking: Broodother Aghs. Broodmother should be disabled immediately until fixed.

### ISSUE THREAD

**Issue by Antelope13** [arcadia-redux/overthrow2#202]
Broodmother's webs allow her to path outside of the map and remain invisible. Her Aghs upgrade allows her to plant traps outside enemies' fountains. In my last game, Broodmother kept going off map, just outside of our fountain. She kept planting traps that kept most of our team in base. If we tried to kill her, she would run off map. Whenever a low-health player would return to base to heal, she would nuke them with Spawn Spiderlings, then hide off-map again.

To reiterate:
You can't kill Broodmother because she's off-map and invisible.
You can't leave your base because of her traps.
You can't earn gold or XP because you can't leave your base.
You can't return to your base with low health because she can nuke you in 1 hit from outside the map.

**Comment by Antelope13** [comment]
Related to #139, reported almost 1 year ago. Winter Wyvern can also path out of the map. 

When Valve made Overthrow 1.0, they disabled heroes that weren't balanced or had bugs on the map. There's no shame in disabling heroes with gamebreaking bugs until they can be fixed.

**Comment by Draze22** [comment]
Will be fixed by https://github.com/arcadia-redux/12v12/issues/531.
