### ISSUE TITLE
Desert Octet minimap is broken

### ISSUE THREAD

**Issue by Draze22** [arcadia-redux/overthrow2#205]
Looks like this at the moment:

![image](https://user-images.githubusercontent.com/63279022/160775860-888f5d70-9cf1-4f56-828c-7e7357578e44.png)

Should look like this:

![image](https://user-images.githubusercontent.com/63279022/160775331-65ac0689-8bf5-41ff-bc1b-0d3df88a7f61.png)

**Comment by GizmoFestus** [comment]
Minimap is fixed now

Also where's discord or repository here in github for overthrow 3.0? I can't find it
