### ISSUE TITLE
One Hour Ban for Players abandoning the game

### ISSUE THREAD

**Issue by Aldrin-John-Olaer-Manalansan** [arcadia-redux/overthrow2#207]
I noticed that there are lots of players who abandons after the match starts without appropriate punishments. I rarely see a team with less players on it win. I feel bad about teams with less players because some of their members left freely without thinking consequences. Not to mention for players that **pursue streak** getting teamed up with a quitter is just a sad turn of events.

The server already enabled 1 hour temporary ban for players who didn't accepted the match, so why not implement this to counter players who intentionally abandon matches? I think its reasonable for this to be implemented.

**Comment by Draze22** [comment]
Unfortunately enabling penalties for leaving games is bugged at the moment (Valve don't seem to want to fix it) and gives every player a ban if the don't reconnect once the game starts. We enabled this for 12v12 because it has pre game time for players to reconnect but it's far too important for players to get to the centre quickly in Overthrow otherwise they would fall behind. Forcing all players to reconnect at the start would give players with slow computers a huge disadvantage and ruin the mode.

**Comment by Aldrin-John-Olaer-Manalansan** [comment]
That's sad to hear, I hope they fixed it right away.

Although I'm also a player who uses a slow computer in which I always gets **disconnected(two red dots hero icon)** after the picking phase. Yes its true that I who experiences that also fall behind, but I do care a lot for the team because I know how hard it is to play with a team of less players(it's hard to win) that's why I always reconnect afterwards. We can always catch up if we fall behind for any reasons and be helpful in some way especially at the late game, unlike the effects if you abandoned the game and didn't contribute at all. On the other hand, Some players doesn't think that way and intentionally **abandons(pure red hero icon)** the match and then join another new lobby of the same mode which is sad to see.

So since the one hour ban doesn't seem reliable maybe at least make a custom penalty for **Abandoning Players** instead of relying on valve's penalty system. Here is my new suggestion's mechanics:
Receive a Win Streak deduction of 1 so that players would think about their actions on abandoning the game. This streak reduction penalty applies only if the following is conditions were met:
    1. The Player Abandoned the Match(pure red hero icon).
    2. Joined a new match of the same arcade mode after he abandoned a match of the same arcade mode.

The streak reduction penalty **will not apply** to any of the following:
    1. Players who only disconnected the game.
    2. Players who went afk through the entire game.


This suggestion isn't perfect, and can be furtherly improved, changed, or balanced if you're interested on applying a **win streak reduction penalty**. Thank you.
